prompt_order = [
  "time",
  "username",
  "directory",
  "git_branch",
  "line_break",
  "character"
]
[username]
show_always = true
[character]
symbol = "ğŸµ"
error_symbol = "ğŸ™ˆ"
use_symbol_for_status = true
[time]
disabled = false
format = "â° [%T]"
utc_time_offset = "-5"
[package]
disabled = true
[nodejs]
disabled = true
[aws]
disabled = true
[git_status]
disabled = true
[git_branch]
symbol = ""
truncation_symbol = ""
[ruby]
disabled = true
[python]
disabled = true
[java]
disabled = true